name: 🔐 Pipeline DevSecOps

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write #pra poder salvar o output do semgrep

jobs:
  pipeline:
    name: Build, Segurança e Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # ✅ PASSO 1: Já está pronto — Baixar o código
      - name: 📥 Checkout do Código
        uses: actions/checkout@v4

      # ✅ PASSO 2: Já está pronto — Build
      - name: ⚙️ Build
        run: |
          echo "Verificando arquivos..."
          ls src/
          echo "Build OK!"

      # ✅ PASSO 3: Secrets Scanning com Gitleaks
      - name: 🔑 Secrets Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ PASSO 4: SAST com Semgrep
      - name: 🔍 SAST - Semgrep
        run: pip install semgrep && semgrep scan --config auto --error --output=semgrep-results.sarif --sarif src/
      
      - name: Envia o resultado .SARIF para a aba de segurança do github
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep-results.sarif

      # ✅ PASSO 5: SCA com Grype
      - name: 📦 SCA - Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

      # ✅ PASSO 6: Já está pronto — Deploy (só roda se tudo passar)
      - name: 🌐 Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: 📤 Upload para Produção
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src'

      - name: 🚀 Deploy em Produção
        id: deployment
        uses: actions/deploy-pages@v4
